/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerConditionDto
 */
export interface ContainerConditionDto {
    /**
     * 
     * @type {string}
     * @memberof ContainerConditionDto
     */
    expression: string;
}

/**
 * Check if a given object implements the ContainerConditionDto interface.
 */
export function instanceOfContainerConditionDto(value: object): value is ContainerConditionDto {
    if (!('expression' in value) || value['expression'] === undefined) return false;
    return true;
}

export function ContainerConditionDtoFromJSON(json: any): ContainerConditionDto {
    return ContainerConditionDtoFromJSONTyped(json, false);
}

export function ContainerConditionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerConditionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'expression': json['expression'],
    };
}

export function ContainerConditionDtoToJSON(value?: ContainerConditionDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'expression': value['expression'],
    };
}

