/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ContainerConditionDto } from './ContainerConditionDto';
import {
    instanceOfContainerConditionDto,
    ContainerConditionDtoFromJSON,
    ContainerConditionDtoFromJSONTyped,
    ContainerConditionDtoToJSON,
} from './ContainerConditionDto';

/**
 * @type ContainerDtoAllOfCondition
 * 
 * @export
 */
export type ContainerDtoAllOfCondition = ContainerConditionDto;

export function ContainerDtoAllOfConditionFromJSON(json: any): ContainerDtoAllOfCondition {
    return ContainerDtoAllOfConditionFromJSONTyped(json, false);
}

export function ContainerDtoAllOfConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerDtoAllOfCondition {
    if (json == null) {
        return json;
    }
    if (instanceOfContainerConditionDto(json)) {
        return ContainerConditionDtoFromJSONTyped(json, true);
    }
}

export function ContainerDtoAllOfConditionToJSON(value?: ContainerDtoAllOfCondition | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfContainerConditionDto(value)) {
        return ContainerConditionDtoToJSON(value as ContainerConditionDto);
    }

    return {};
}

