/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantQuestionnaireInstanceDto } from './TenantQuestionnaireInstanceDto';
import {
    TenantQuestionnaireInstanceDtoFromJSON,
    TenantQuestionnaireInstanceDtoFromJSONTyped,
    TenantQuestionnaireInstanceDtoToJSON,
} from './TenantQuestionnaireInstanceDto';

/**
 * 
 * @export
 * @interface PaginatedListOfTenantQuestionnaireInstanceDto
 */
export interface PaginatedListOfTenantQuestionnaireInstanceDto {
    /**
     * 
     * @type {Array<TenantQuestionnaireInstanceDto>}
     * @memberof PaginatedListOfTenantQuestionnaireInstanceDto
     */
    items: Array<TenantQuestionnaireInstanceDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfTenantQuestionnaireInstanceDto
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfTenantQuestionnaireInstanceDto
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfTenantQuestionnaireInstanceDto
     */
    totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfTenantQuestionnaireInstanceDto
     */
    hasPreviousPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfTenantQuestionnaireInstanceDto
     */
    hasNextPage: boolean;
}

/**
 * Check if a given object implements the PaginatedListOfTenantQuestionnaireInstanceDto interface.
 */
export function instanceOfPaginatedListOfTenantQuestionnaireInstanceDto(value: object): value is PaginatedListOfTenantQuestionnaireInstanceDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    return true;
}

export function PaginatedListOfTenantQuestionnaireInstanceDtoFromJSON(json: any): PaginatedListOfTenantQuestionnaireInstanceDto {
    return PaginatedListOfTenantQuestionnaireInstanceDtoFromJSONTyped(json, false);
}

export function PaginatedListOfTenantQuestionnaireInstanceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListOfTenantQuestionnaireInstanceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TenantQuestionnaireInstanceDtoFromJSON)),
        'pageNumber': json['pageNumber'],
        'totalPages': json['totalPages'],
        'totalCount': json['totalCount'],
        'hasPreviousPage': json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'],
    };
}

export function PaginatedListOfTenantQuestionnaireInstanceDtoToJSON(value?: PaginatedListOfTenantQuestionnaireInstanceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(TenantQuestionnaireInstanceDtoToJSON)),
        'pageNumber': value['pageNumber'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

