/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantDto2 } from './TenantDto2';
import {
    TenantDto2FromJSON,
    TenantDto2FromJSONTyped,
    TenantDto2ToJSON,
} from './TenantDto2';
import type { ProjectDtoAllOfAsset } from './ProjectDtoAllOfAsset';
import {
    ProjectDtoAllOfAssetFromJSON,
    ProjectDtoAllOfAssetFromJSONTyped,
    ProjectDtoAllOfAssetToJSON,
} from './ProjectDtoAllOfAsset';
import type { LanguageDto } from './LanguageDto';
import {
    LanguageDtoFromJSON,
    LanguageDtoFromJSONTyped,
    LanguageDtoToJSON,
} from './LanguageDto';
import type { InternationalizedString } from './InternationalizedString';
import {
    InternationalizedStringFromJSON,
    InternationalizedStringFromJSONTyped,
    InternationalizedStringToJSON,
} from './InternationalizedString';
import type { ProjectDtoAllOfParticipationState } from './ProjectDtoAllOfParticipationState';
import {
    ProjectDtoAllOfParticipationStateFromJSON,
    ProjectDtoAllOfParticipationStateFromJSONTyped,
    ProjectDtoAllOfParticipationStateToJSON,
} from './ProjectDtoAllOfParticipationState';

/**
 * 
 * @export
 * @interface ProjectDto
 */
export interface ProjectDto {
    /**
     * 
     * @type {string}
     * @memberof ProjectDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDto
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDto
     */
    name: string;
    /**
     * 
     * @type {InternationalizedString}
     * @memberof ProjectDto
     */
    title: InternationalizedString;
    /**
     * 
     * @type {InternationalizedString}
     * @memberof ProjectDto
     */
    shortDescription: InternationalizedString;
    /**
     * 
     * @type {ProjectDtoAllOfAsset}
     * @memberof ProjectDto
     */
    asset?: ProjectDtoAllOfAsset;
    /**
     * 
     * @type {Date}
     * @memberof ProjectDto
     */
    published?: Date;
    /**
     * 
     * @type {Array<LanguageDto>}
     * @memberof ProjectDto
     */
    languages: Array<LanguageDto>;
    /**
     * 
     * @type {ProjectDtoAllOfParticipationState}
     * @memberof ProjectDto
     */
    participationState?: ProjectDtoAllOfParticipationState;
    /**
     * 
     * @type {TenantDto2}
     * @memberof ProjectDto
     */
    tenant: TenantDto2;
}

/**
 * Check if a given object implements the ProjectDto interface.
 */
export function instanceOfProjectDto(value: object): value is ProjectDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('shortDescription' in value) || value['shortDescription'] === undefined) return false;
    if (!('languages' in value) || value['languages'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    return true;
}

export function ProjectDtoFromJSON(json: any): ProjectDto {
    return ProjectDtoFromJSONTyped(json, false);
}

export function ProjectDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'name': json['name'],
        'title': InternationalizedStringFromJSON(json['title']),
        'shortDescription': InternationalizedStringFromJSON(json['shortDescription']),
        'asset': json['asset'] == null ? undefined : ProjectDtoAllOfAssetFromJSON(json['asset']),
        'published': json['published'] == null ? undefined : (new Date(json['published'])),
        'languages': ((json['languages'] as Array<any>).map(LanguageDtoFromJSON)),
        'participationState': json['participationState'] == null ? undefined : ProjectDtoAllOfParticipationStateFromJSON(json['participationState']),
        'tenant': TenantDto2FromJSON(json['tenant']),
    };
}

export function ProjectDtoToJSON(value?: ProjectDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'name': value['name'],
        'title': InternationalizedStringToJSON(value['title']),
        'shortDescription': InternationalizedStringToJSON(value['shortDescription']),
        'asset': ProjectDtoAllOfAssetToJSON(value['asset']),
        'published': value['published'] == null ? undefined : ((value['published'] as any).toISOString()),
        'languages': ((value['languages'] as Array<any>).map(LanguageDtoToJSON)),
        'participationState': ProjectDtoAllOfParticipationStateToJSON(value['participationState']),
        'tenant': TenantDto2ToJSON(value['tenant']),
    };
}

