/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantDetailsDto
 */
export interface TenantDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof TenantDetailsDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TenantDetailsDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TenantDetailsDto
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof TenantDetailsDto
     */
    url: string;
}

/**
 * Check if a given object implements the TenantDetailsDto interface.
 */
export function instanceOfTenantDetailsDto(value: object): value is TenantDetailsDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function TenantDetailsDtoFromJSON(json: any): TenantDetailsDto {
    return TenantDetailsDtoFromJSONTyped(json, false);
}

export function TenantDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'url': json['url'],
    };
}

export function TenantDetailsDtoToJSON(value?: TenantDetailsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'url': value['url'],
    };
}

