/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TenantParticipationState = {
    NotParticipating: 'notParticipating',
    Participating: 'participating'
} as const;
export type TenantParticipationState = typeof TenantParticipationState[keyof typeof TenantParticipationState];


export function instanceOfTenantParticipationState(value: any): boolean {
    for (const key in TenantParticipationState) {
        if (Object.prototype.hasOwnProperty.call(TenantParticipationState, key)) {
            if (TenantParticipationState[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TenantParticipationStateFromJSON(json: any): TenantParticipationState {
    return TenantParticipationStateFromJSONTyped(json, false);
}

export function TenantParticipationStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantParticipationState {
    return json as TenantParticipationState;
}

export function TenantParticipationStateToJSON(value?: TenantParticipationState | null): any {
    return value as any;
}

