/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TenantParticipationState } from './TenantParticipationState';
import {
    instanceOfTenantParticipationState,
    TenantParticipationStateFromJSON,
    TenantParticipationStateFromJSONTyped,
    TenantParticipationStateToJSON,
} from './TenantParticipationState';

/**
 * @type TenantDto2ParticipationState
 * 
 * @export
 */
export type TenantDto2ParticipationState = TenantParticipationState;

export function TenantDto2ParticipationStateFromJSON(json: any): TenantDto2ParticipationState {
    return TenantDto2ParticipationStateFromJSONTyped(json, false);
}

export function TenantDto2ParticipationStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDto2ParticipationState {
    if (json == null) {
        return json;
    }
    if (instanceOfTenantParticipationState(json)) {
        return TenantParticipationStateFromJSONTyped(json, true);
    }
}

export function TenantDto2ParticipationStateToJSON(value?: TenantDto2ParticipationState | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfTenantParticipationState(value)) {
        return TenantParticipationStateToJSON(value as TenantParticipationState);
    }

    return {};
}

