/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnswerDto } from './AnswerDto';
import {
    AnswerDtoFromJSON,
    AnswerDtoFromJSONTyped,
    AnswerDtoToJSON,
} from './AnswerDto';

/**
 * 
 * @export
 * @interface ChoiceAnswerDto
 */
export interface ChoiceAnswerDto extends AnswerDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof ChoiceAnswerDto
     */
    values?: Array<string>;
}

/**
 * Check if a given object implements the ChoiceAnswerDto interface.
 */
export function instanceOfChoiceAnswerDto(value: object): value is ChoiceAnswerDto {
    return true;
}

export function ChoiceAnswerDtoFromJSON(json: any): ChoiceAnswerDto {
    return ChoiceAnswerDtoFromJSONTyped(json, false);
}

export function ChoiceAnswerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChoiceAnswerDto {
    if (json == null) {
        return json;
    }
    return {
        ...AnswerDtoFromJSONTyped(json, ignoreDiscriminator),
        'values': json['values'] == null ? undefined : json['values'],
    };
}

export function ChoiceAnswerDtoToJSON(value?: ChoiceAnswerDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...AnswerDtoToJSON(value),
        'values': value['values'],
    };
}

