/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ChoiceValueDto } from './ChoiceValueDto';
import {
    instanceOfChoiceValueDto,
    ChoiceValueDtoFromJSON,
    ChoiceValueDtoFromJSONTyped,
    ChoiceValueDtoToJSON,
} from './ChoiceValueDto';

/**
 * @type ChoicePropertyDtoAllOfValue
 * 
 * @export
 */
export type ChoicePropertyDtoAllOfValue = ChoiceValueDto;

export function ChoicePropertyDtoAllOfValueFromJSON(json: any): ChoicePropertyDtoAllOfValue {
    return ChoicePropertyDtoAllOfValueFromJSONTyped(json, false);
}

export function ChoicePropertyDtoAllOfValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChoicePropertyDtoAllOfValue {
    if (json == null) {
        return json;
    }
    if (instanceOfChoiceValueDto(json)) {
        return ChoiceValueDtoFromJSONTyped(json, true);
    }
}

export function ChoicePropertyDtoAllOfValueToJSON(value?: ChoicePropertyDtoAllOfValue | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfChoiceValueDto(value)) {
        return ChoiceValueDtoToJSON(value as ChoiceValueDto);
    }

    return {};
}

