/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValueDto } from './ValueDto';
import {
    ValueDtoFromJSON,
    ValueDtoFromJSONTyped,
    ValueDtoToJSON,
} from './ValueDto';

/**
 * 
 * @export
 * @interface ChoiceValueDto
 */
export interface ChoiceValueDto extends ValueDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof ChoiceValueDto
     */
    values?: Array<string>;
}

/**
 * Check if a given object implements the ChoiceValueDto interface.
 */
export function instanceOfChoiceValueDto(value: object): value is ChoiceValueDto {
    return true;
}

export function ChoiceValueDtoFromJSON(json: any): ChoiceValueDto {
    return ChoiceValueDtoFromJSONTyped(json, false);
}

export function ChoiceValueDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChoiceValueDto {
    if (json == null) {
        return json;
    }
    return {
        ...ValueDtoFromJSONTyped(json, ignoreDiscriminator),
        'values': json['values'] == null ? undefined : json['values'],
    };
}

export function ChoiceValueDtoToJSON(value?: ChoiceValueDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...ValueDtoToJSON(value),
        'values': value['values'],
    };
}

