/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ChoiceAnswerDto } from './ChoiceAnswerDto';
import {
    instanceOfChoiceAnswerDto,
    ChoiceAnswerDtoFromJSON,
    ChoiceAnswerDtoFromJSONTyped,
    ChoiceAnswerDtoToJSON,
} from './ChoiceAnswerDto';

/**
 * @type ChoiceQuestionDtoAllOfAnswer
 * 
 * @export
 */
export type ChoiceQuestionDtoAllOfAnswer = ChoiceAnswerDto;

export function ChoiceQuestionDtoAllOfAnswerFromJSON(json: any): ChoiceQuestionDtoAllOfAnswer {
    return ChoiceQuestionDtoAllOfAnswerFromJSONTyped(json, false);
}

export function ChoiceQuestionDtoAllOfAnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChoiceQuestionDtoAllOfAnswer {
    if (json == null) {
        return json;
    }
    if (instanceOfChoiceAnswerDto(json)) {
        return ChoiceAnswerDtoFromJSONTyped(json, true);
    }
}

export function ChoiceQuestionDtoAllOfAnswerToJSON(value?: ChoiceQuestionDtoAllOfAnswer | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfChoiceAnswerDto(value)) {
        return ChoiceAnswerDtoToJSON(value as ChoiceAnswerDto);
    }

    return {};
}

