/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SharingState } from './SharingState';
import {
    SharingStateFromJSON,
    SharingStateFromJSONTyped,
    SharingStateToJSON,
} from './SharingState';

/**
 * 
 * @export
 * @interface ContextObjectInstanceDto
 */
export interface ContextObjectInstanceDto {
    /**
     * 
     * @type {string}
     * @memberof ContextObjectInstanceDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ContextObjectInstanceDto
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof ContextObjectInstanceDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ContextObjectInstanceDto
     */
    contextObjectId: string;
    /**
     * 
     * @type {number}
     * @memberof ContextObjectInstanceDto
     */
    contextObjectVersion: number;
    /**
     * 
     * @type {string}
     * @memberof ContextObjectInstanceDto
     */
    contextObjectName: string;
    /**
     * 
     * @type {SharingState}
     * @memberof ContextObjectInstanceDto
     */
    sharingState: SharingState;
}

/**
 * Check if a given object implements the ContextObjectInstanceDto interface.
 */
export function instanceOfContextObjectInstanceDto(value: object): value is ContextObjectInstanceDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('contextObjectId' in value) || value['contextObjectId'] === undefined) return false;
    if (!('contextObjectVersion' in value) || value['contextObjectVersion'] === undefined) return false;
    if (!('contextObjectName' in value) || value['contextObjectName'] === undefined) return false;
    if (!('sharingState' in value) || value['sharingState'] === undefined) return false;
    return true;
}

export function ContextObjectInstanceDtoFromJSON(json: any): ContextObjectInstanceDto {
    return ContextObjectInstanceDtoFromJSONTyped(json, false);
}

export function ContextObjectInstanceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContextObjectInstanceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'name': json['name'],
        'contextObjectId': json['contextObjectId'],
        'contextObjectVersion': json['contextObjectVersion'],
        'contextObjectName': json['contextObjectName'],
        'sharingState': SharingStateFromJSON(json['sharingState']),
    };
}

export function ContextObjectInstanceDtoToJSON(value?: ContextObjectInstanceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'name': value['name'],
        'contextObjectId': value['contextObjectId'],
        'contextObjectVersion': value['contextObjectVersion'],
        'contextObjectName': value['contextObjectName'],
        'sharingState': SharingStateToJSON(value['sharingState']),
    };
}

