/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentDto } from './ContentDto';
import {
    ContentDtoFromJSON,
    ContentDtoFromJSONTyped,
    ContentDtoToJSON,
} from './ContentDto';
import type { ElementType } from './ElementType';
import {
    ElementTypeFromJSON,
    ElementTypeFromJSONTyped,
    ElementTypeToJSON,
} from './ElementType';
import type { ContentDtoCondition } from './ContentDtoCondition';
import {
    ContentDtoConditionFromJSON,
    ContentDtoConditionFromJSONTyped,
    ContentDtoConditionToJSON,
} from './ContentDtoCondition';
import type { InternationalizedString } from './InternationalizedString';
import {
    InternationalizedStringFromJSON,
    InternationalizedStringFromJSONTyped,
    InternationalizedStringToJSON,
} from './InternationalizedString';

/**
 * 
 * @export
 * @interface ContentPageDto
 */
export interface ContentPageDto extends ContentDto {
    /**
     * 
     * @type {InternationalizedString}
     * @memberof ContentPageDto
     */
    title: InternationalizedString;
    /**
     * 
     * @type {Array<ContentDto>}
     * @memberof ContentPageDto
     */
    contents: Array<ContentDto>;
}

/**
 * Check if a given object implements the ContentPageDto interface.
 */
export function instanceOfContentPageDto(value: object): value is ContentPageDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('contents' in value) || value['contents'] === undefined) return false;
    return true;
}

export function ContentPageDtoFromJSON(json: any): ContentPageDto {
    return ContentPageDtoFromJSONTyped(json, false);
}

export function ContentPageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentPageDto {
    if (json == null) {
        return json;
    }
    return {
        ...ContentDtoFromJSONTyped(json, ignoreDiscriminator),
        'title': InternationalizedStringFromJSON(json['title']),
        'contents': ((json['contents'] as Array<any>).map(ContentDtoFromJSON)),
    };
}

export function ContentPageDtoToJSON(value?: ContentPageDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...ContentDtoToJSON(value),
        'title': InternationalizedStringToJSON(value['title']),
        'contents': ((value['contents'] as Array<any>).map(ContentDtoToJSON)),
    };
}

