/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentCondition
 */
export interface ContentCondition {
    /**
     * 
     * @type {string}
     * @memberof ContentCondition
     */
    expression: string;
}

/**
 * Check if a given object implements the ContentCondition interface.
 */
export function instanceOfContentCondition(value: object): value is ContentCondition {
    if (!('expression' in value) || value['expression'] === undefined) return false;
    return true;
}

export function ContentConditionFromJSON(json: any): ContentCondition {
    return ContentConditionFromJSONTyped(json, false);
}

export function ContentConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentCondition {
    if (json == null) {
        return json;
    }
    return {
        
        'expression': json['expression'],
    };
}

export function ContentConditionToJSON(value?: ContentCondition | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'expression': value['expression'],
    };
}

