/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContainerDetailsDtoAllOfCondition } from './ContainerDetailsDtoAllOfCondition';
import {
    ContainerDetailsDtoAllOfConditionFromJSON,
    ContainerDetailsDtoAllOfConditionFromJSONTyped,
    ContainerDetailsDtoAllOfConditionToJSON,
} from './ContainerDetailsDtoAllOfCondition';
import type { LanguageDto } from './LanguageDto';
import {
    LanguageDtoFromJSON,
    LanguageDtoFromJSONTyped,
    LanguageDtoToJSON,
} from './LanguageDto';
import type { InternationalizedString } from './InternationalizedString';
import {
    InternationalizedStringFromJSON,
    InternationalizedStringFromJSONTyped,
    InternationalizedStringToJSON,
} from './InternationalizedString';
import type { InternationalizedDocument } from './InternationalizedDocument';
import {
    InternationalizedDocumentFromJSON,
    InternationalizedDocumentFromJSONTyped,
    InternationalizedDocumentToJSON,
} from './InternationalizedDocument';

/**
 * 
 * @export
 * @interface ContainerDetailsDto
 */
export interface ContainerDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof ContainerDetailsDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerDetailsDto
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerDetailsDto
     */
    name: string;
    /**
     * 
     * @type {InternationalizedString}
     * @memberof ContainerDetailsDto
     */
    title: InternationalizedString;
    /**
     * 
     * @type {InternationalizedDocument}
     * @memberof ContainerDetailsDto
     */
    description: InternationalizedDocument;
    /**
     * 
     * @type {ContainerDetailsDtoAllOfCondition}
     * @memberof ContainerDetailsDto
     */
    condition?: ContainerDetailsDtoAllOfCondition;
    /**
     * 
     * @type {Array<LanguageDto>}
     * @memberof ContainerDetailsDto
     */
    languages: Array<LanguageDto>;
}

/**
 * Check if a given object implements the ContainerDetailsDto interface.
 */
export function instanceOfContainerDetailsDto(value: object): value is ContainerDetailsDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('languages' in value) || value['languages'] === undefined) return false;
    return true;
}

export function ContainerDetailsDtoFromJSON(json: any): ContainerDetailsDto {
    return ContainerDetailsDtoFromJSONTyped(json, false);
}

export function ContainerDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'name': json['name'],
        'title': InternationalizedStringFromJSON(json['title']),
        'description': InternationalizedDocumentFromJSON(json['description']),
        'condition': json['condition'] == null ? undefined : ContainerDetailsDtoAllOfConditionFromJSON(json['condition']),
        'languages': ((json['languages'] as Array<any>).map(LanguageDtoFromJSON)),
    };
}

export function ContainerDetailsDtoToJSON(value?: ContainerDetailsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'name': value['name'],
        'title': InternationalizedStringToJSON(value['title']),
        'description': InternationalizedDocumentToJSON(value['description']),
        'condition': ContainerDetailsDtoAllOfConditionToJSON(value['condition']),
        'languages': ((value['languages'] as Array<any>).map(LanguageDtoToJSON)),
    };
}

