/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DateValueDto } from './DateValueDto';
import {
    instanceOfDateValueDto,
    DateValueDtoFromJSON,
    DateValueDtoFromJSONTyped,
    DateValueDtoToJSON,
} from './DateValueDto';

/**
 * @type DatePropertyDtoAllOfValue
 * 
 * @export
 */
export type DatePropertyDtoAllOfValue = DateValueDto;

export function DatePropertyDtoAllOfValueFromJSON(json: any): DatePropertyDtoAllOfValue {
    return DatePropertyDtoAllOfValueFromJSONTyped(json, false);
}

export function DatePropertyDtoAllOfValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatePropertyDtoAllOfValue {
    if (json == null) {
        return json;
    }
    if (instanceOfDateValueDto(json)) {
        return DateValueDtoFromJSONTyped(json, true);
    }
}

export function DatePropertyDtoAllOfValueToJSON(value?: DatePropertyDtoAllOfValue | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfDateValueDto(value)) {
        return DateValueDtoToJSON(value as DateValueDto);
    }

    return {};
}

