/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentDto } from './ContentDto';
import {
    ContentDtoFromJSON,
    ContentDtoFromJSONTyped,
    ContentDtoToJSON,
} from './ContentDto';
import type { ElementType } from './ElementType';
import {
    ElementTypeFromJSON,
    ElementTypeFromJSONTyped,
    ElementTypeToJSON,
} from './ElementType';
import type { ContentDtoCondition } from './ContentDtoCondition';
import {
    ContentDtoConditionFromJSON,
    ContentDtoConditionFromJSONTyped,
    ContentDtoConditionToJSON,
} from './ContentDtoCondition';

/**
 * 
 * @export
 * @interface DisplayDto
 */
export interface DisplayDto extends ContentDto {
}

/**
 * Check if a given object implements the DisplayDto interface.
 */
export function instanceOfDisplayDto(value: object): value is DisplayDto {
    return true;
}

export function DisplayDtoFromJSON(json: any): DisplayDto {
    return DisplayDtoFromJSONTyped(json, false);
}

export function DisplayDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisplayDto {
    return json;
}

export function DisplayDtoToJSON(value?: DisplayDto | null): any {
    return value;
}

