/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionValidation } from './QuestionValidation';
import {
    QuestionValidationFromJSON,
    QuestionValidationFromJSONTyped,
    QuestionValidationToJSON,
} from './QuestionValidation';

/**
 * 
 * @export
 * @interface LikertQuestionValidation
 */
export interface LikertQuestionValidation extends QuestionValidation {
}

/**
 * Check if a given object implements the LikertQuestionValidation interface.
 */
export function instanceOfLikertQuestionValidation(value: object): value is LikertQuestionValidation {
    return true;
}

export function LikertQuestionValidationFromJSON(json: any): LikertQuestionValidation {
    return LikertQuestionValidationFromJSONTyped(json, false);
}

export function LikertQuestionValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikertQuestionValidation {
    return json;
}

export function LikertQuestionValidationToJSON(value?: LikertQuestionValidation | null): any {
    return value;
}

