/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnswerDto } from './AnswerDto';
import {
    AnswerDtoFromJSON,
    AnswerDtoFromJSONTyped,
    AnswerDtoToJSON,
} from './AnswerDto';

/**
 * 
 * @export
 * @interface LikertAnswerDto
 */
export interface LikertAnswerDto extends AnswerDto {
    /**
     * 
     * @type {string}
     * @memberof LikertAnswerDto
     */
    value?: string;
}

/**
 * Check if a given object implements the LikertAnswerDto interface.
 */
export function instanceOfLikertAnswerDto(value: object): value is LikertAnswerDto {
    return true;
}

export function LikertAnswerDtoFromJSON(json: any): LikertAnswerDto {
    return LikertAnswerDtoFromJSONTyped(json, false);
}

export function LikertAnswerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikertAnswerDto {
    if (json == null) {
        return json;
    }
    return {
        ...AnswerDtoFromJSONTyped(json, ignoreDiscriminator),
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function LikertAnswerDtoToJSON(value?: LikertAnswerDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...AnswerDtoToJSON(value),
        'value': value['value'],
    };
}

