/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ElementType } from './ElementType';
import {
    ElementTypeFromJSON,
    ElementTypeFromJSONTyped,
    ElementTypeToJSON,
} from './ElementType';
import type { NumberPropertyValidation } from './NumberPropertyValidation';
import {
    NumberPropertyValidationFromJSON,
    NumberPropertyValidationFromJSONTyped,
    NumberPropertyValidationToJSON,
} from './NumberPropertyValidation';
import type { ContentDtoCondition } from './ContentDtoCondition';
import {
    ContentDtoConditionFromJSON,
    ContentDtoConditionFromJSONTyped,
    ContentDtoConditionToJSON,
} from './ContentDtoCondition';
import type { InternationalizedString } from './InternationalizedString';
import {
    InternationalizedStringFromJSON,
    InternationalizedStringFromJSONTyped,
    InternationalizedStringToJSON,
} from './InternationalizedString';
import type { NumberPropertyDtoAllOfValue } from './NumberPropertyDtoAllOfValue';
import {
    NumberPropertyDtoAllOfValueFromJSON,
    NumberPropertyDtoAllOfValueFromJSONTyped,
    NumberPropertyDtoAllOfValueToJSON,
} from './NumberPropertyDtoAllOfValue';
import type { PropertyDto } from './PropertyDto';
import {
    PropertyDtoFromJSON,
    PropertyDtoFromJSONTyped,
    PropertyDtoToJSON,
} from './PropertyDto';

/**
 * 
 * @export
 * @interface NumberPropertyDto
 */
export interface NumberPropertyDto extends PropertyDto {
    /**
     * 
     * @type {NumberPropertyValidation}
     * @memberof NumberPropertyDto
     */
    validation: NumberPropertyValidation;
    /**
     * 
     * @type {NumberPropertyDtoAllOfValue}
     * @memberof NumberPropertyDto
     */
    value?: NumberPropertyDtoAllOfValue;
}

/**
 * Check if a given object implements the NumberPropertyDto interface.
 */
export function instanceOfNumberPropertyDto(value: object): value is NumberPropertyDto {
    if (!('validation' in value) || value['validation'] === undefined) return false;
    return true;
}

export function NumberPropertyDtoFromJSON(json: any): NumberPropertyDto {
    return NumberPropertyDtoFromJSONTyped(json, false);
}

export function NumberPropertyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberPropertyDto {
    if (json == null) {
        return json;
    }
    return {
        ...PropertyDtoFromJSONTyped(json, ignoreDiscriminator),
        'validation': NumberPropertyValidationFromJSON(json['validation']),
        'value': json['value'] == null ? undefined : NumberPropertyDtoAllOfValueFromJSON(json['value']),
    };
}

export function NumberPropertyDtoToJSON(value?: NumberPropertyDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...PropertyDtoToJSON(value),
        'validation': NumberPropertyValidationToJSON(value['validation']),
        'value': NumberPropertyDtoAllOfValueToJSON(value['value']),
    };
}

