/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionnaireDto } from './QuestionnaireDto';
import {
    QuestionnaireDtoFromJSON,
    QuestionnaireDtoFromJSONTyped,
    QuestionnaireDtoToJSON,
} from './QuestionnaireDto';

/**
 * 
 * @export
 * @interface PaginatedListOfQuestionnaireDto
 */
export interface PaginatedListOfQuestionnaireDto {
    /**
     * 
     * @type {Array<QuestionnaireDto>}
     * @memberof PaginatedListOfQuestionnaireDto
     */
    items: Array<QuestionnaireDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfQuestionnaireDto
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfQuestionnaireDto
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfQuestionnaireDto
     */
    totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfQuestionnaireDto
     */
    hasPreviousPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfQuestionnaireDto
     */
    hasNextPage: boolean;
}

/**
 * Check if a given object implements the PaginatedListOfQuestionnaireDto interface.
 */
export function instanceOfPaginatedListOfQuestionnaireDto(value: object): value is PaginatedListOfQuestionnaireDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    return true;
}

export function PaginatedListOfQuestionnaireDtoFromJSON(json: any): PaginatedListOfQuestionnaireDto {
    return PaginatedListOfQuestionnaireDtoFromJSONTyped(json, false);
}

export function PaginatedListOfQuestionnaireDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListOfQuestionnaireDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(QuestionnaireDtoFromJSON)),
        'pageNumber': json['pageNumber'],
        'totalPages': json['totalPages'],
        'totalCount': json['totalCount'],
        'hasPreviousPage': json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'],
    };
}

export function PaginatedListOfQuestionnaireDtoToJSON(value?: PaginatedListOfQuestionnaireDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(QuestionnaireDtoToJSON)),
        'pageNumber': value['pageNumber'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

