/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceDto } from './DeviceDto';
import {
    DeviceDtoFromJSON,
    DeviceDtoFromJSONTyped,
    DeviceDtoToJSON,
} from './DeviceDto';

/**
 * 
 * @export
 * @interface PaginatedListOfDeviceDto
 */
export interface PaginatedListOfDeviceDto {
    /**
     * 
     * @type {Array<DeviceDto>}
     * @memberof PaginatedListOfDeviceDto
     */
    items: Array<DeviceDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfDeviceDto
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfDeviceDto
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfDeviceDto
     */
    totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfDeviceDto
     */
    hasPreviousPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfDeviceDto
     */
    hasNextPage: boolean;
}

/**
 * Check if a given object implements the PaginatedListOfDeviceDto interface.
 */
export function instanceOfPaginatedListOfDeviceDto(value: object): value is PaginatedListOfDeviceDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    return true;
}

export function PaginatedListOfDeviceDtoFromJSON(json: any): PaginatedListOfDeviceDto {
    return PaginatedListOfDeviceDtoFromJSONTyped(json, false);
}

export function PaginatedListOfDeviceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListOfDeviceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(DeviceDtoFromJSON)),
        'pageNumber': json['pageNumber'],
        'totalPages': json['totalPages'],
        'totalCount': json['totalCount'],
        'hasPreviousPage': json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'],
    };
}

export function PaginatedListOfDeviceDtoToJSON(value?: PaginatedListOfDeviceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(DeviceDtoToJSON)),
        'pageNumber': value['pageNumber'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

