/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ProjectParticipationState } from './ProjectParticipationState';
import {
    instanceOfProjectParticipationState,
    ProjectParticipationStateFromJSON,
    ProjectParticipationStateFromJSONTyped,
    ProjectParticipationStateToJSON,
} from './ProjectParticipationState';

/**
 * @type ProjectDetailsDtoAllOfParticipationState
 * 
 * @export
 */
export type ProjectDetailsDtoAllOfParticipationState = ProjectParticipationState;

export function ProjectDetailsDtoAllOfParticipationStateFromJSON(json: any): ProjectDetailsDtoAllOfParticipationState {
    return ProjectDetailsDtoAllOfParticipationStateFromJSONTyped(json, false);
}

export function ProjectDetailsDtoAllOfParticipationStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDetailsDtoAllOfParticipationState {
    if (json == null) {
        return json;
    }
    if (instanceOfProjectParticipationState(json)) {
        return ProjectParticipationStateFromJSONTyped(json, true);
    }
}

export function ProjectDetailsDtoAllOfParticipationStateToJSON(value?: ProjectDetailsDtoAllOfParticipationState | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfProjectParticipationState(value)) {
        return ProjectParticipationStateToJSON(value as ProjectParticipationState);
    }

    return {};
}

