/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageDto } from './LanguageDto';
import {
    LanguageDtoFromJSON,
    LanguageDtoFromJSONTyped,
    LanguageDtoToJSON,
} from './LanguageDto';
import type { InternationalizedString } from './InternationalizedString';
import {
    InternationalizedStringFromJSON,
    InternationalizedStringFromJSONTyped,
    InternationalizedStringToJSON,
} from './InternationalizedString';
import type { ContainerDtoAllOfCondition } from './ContainerDtoAllOfCondition';
import {
    ContainerDtoAllOfConditionFromJSON,
    ContainerDtoAllOfConditionFromJSONTyped,
    ContainerDtoAllOfConditionToJSON,
} from './ContainerDtoAllOfCondition';
import type { QuestionnaireInstantiationMode } from './QuestionnaireInstantiationMode';
import {
    QuestionnaireInstantiationModeFromJSON,
    QuestionnaireInstantiationModeFromJSONTyped,
    QuestionnaireInstantiationModeToJSON,
} from './QuestionnaireInstantiationMode';

/**
 * 
 * @export
 * @interface QuestionnaireDto
 */
export interface QuestionnaireDto {
    /**
     * 
     * @type {string}
     * @memberof QuestionnaireDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionnaireDto
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionnaireDto
     */
    name: string;
    /**
     * 
     * @type {InternationalizedString}
     * @memberof QuestionnaireDto
     */
    title: InternationalizedString;
    /**
     * 
     * @type {ContainerDtoAllOfCondition}
     * @memberof QuestionnaireDto
     */
    condition?: ContainerDtoAllOfCondition;
    /**
     * 
     * @type {Array<LanguageDto>}
     * @memberof QuestionnaireDto
     */
    languages: Array<LanguageDto>;
    /**
     * 
     * @type {QuestionnaireInstantiationMode}
     * @memberof QuestionnaireDto
     */
    instantiationMode: QuestionnaireInstantiationMode;
}

/**
 * Check if a given object implements the QuestionnaireDto interface.
 */
export function instanceOfQuestionnaireDto(value: object): value is QuestionnaireDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('languages' in value) || value['languages'] === undefined) return false;
    if (!('instantiationMode' in value) || value['instantiationMode'] === undefined) return false;
    return true;
}

export function QuestionnaireDtoFromJSON(json: any): QuestionnaireDto {
    return QuestionnaireDtoFromJSONTyped(json, false);
}

export function QuestionnaireDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionnaireDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'name': json['name'],
        'title': InternationalizedStringFromJSON(json['title']),
        'condition': json['condition'] == null ? undefined : ContainerDtoAllOfConditionFromJSON(json['condition']),
        'languages': ((json['languages'] as Array<any>).map(LanguageDtoFromJSON)),
        'instantiationMode': QuestionnaireInstantiationModeFromJSON(json['instantiationMode']),
    };
}

export function QuestionnaireDtoToJSON(value?: QuestionnaireDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'name': value['name'],
        'title': InternationalizedStringToJSON(value['title']),
        'condition': ContainerDtoAllOfConditionToJSON(value['condition']),
        'languages': ((value['languages'] as Array<any>).map(LanguageDtoToJSON)),
        'instantiationMode': QuestionnaireInstantiationModeToJSON(value['instantiationMode']),
    };
}

