/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterAppInstallationCommand
 */
export interface RegisterAppInstallationCommand {
    /**
     * 
     * @type {string}
     * @memberof RegisterAppInstallationCommand
     */
    deviceName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAppInstallationCommand
     */
    deviceIdentifier: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAppInstallationCommand
     */
    deviceModel: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAppInstallationCommand
     */
    deviceOsVersion: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAppInstallationCommand
     */
    deviceLanguage: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAppInstallationCommand
     */
    deviceTimezone: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAppInstallationCommand
     */
    appIdentifier: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAppInstallationCommand
     */
    appPushToken: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAppInstallationCommand
     */
    appPushBase64PublicKey: string;
}

/**
 * Check if a given object implements the RegisterAppInstallationCommand interface.
 */
export function instanceOfRegisterAppInstallationCommand(value: object): value is RegisterAppInstallationCommand {
    if (!('deviceName' in value) || value['deviceName'] === undefined) return false;
    if (!('deviceIdentifier' in value) || value['deviceIdentifier'] === undefined) return false;
    if (!('deviceModel' in value) || value['deviceModel'] === undefined) return false;
    if (!('deviceOsVersion' in value) || value['deviceOsVersion'] === undefined) return false;
    if (!('deviceLanguage' in value) || value['deviceLanguage'] === undefined) return false;
    if (!('deviceTimezone' in value) || value['deviceTimezone'] === undefined) return false;
    if (!('appIdentifier' in value) || value['appIdentifier'] === undefined) return false;
    if (!('appPushToken' in value) || value['appPushToken'] === undefined) return false;
    if (!('appPushBase64PublicKey' in value) || value['appPushBase64PublicKey'] === undefined) return false;
    return true;
}

export function RegisterAppInstallationCommandFromJSON(json: any): RegisterAppInstallationCommand {
    return RegisterAppInstallationCommandFromJSONTyped(json, false);
}

export function RegisterAppInstallationCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterAppInstallationCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceName': json['deviceName'],
        'deviceIdentifier': json['deviceIdentifier'],
        'deviceModel': json['deviceModel'],
        'deviceOsVersion': json['deviceOsVersion'],
        'deviceLanguage': json['deviceLanguage'],
        'deviceTimezone': json['deviceTimezone'],
        'appIdentifier': json['appIdentifier'],
        'appPushToken': json['appPushToken'],
        'appPushBase64PublicKey': json['appPushBase64PublicKey'],
    };
}

export function RegisterAppInstallationCommandToJSON(value?: RegisterAppInstallationCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'deviceName': value['deviceName'],
        'deviceIdentifier': value['deviceIdentifier'],
        'deviceModel': value['deviceModel'],
        'deviceOsVersion': value['deviceOsVersion'],
        'deviceLanguage': value['deviceLanguage'],
        'deviceTimezone': value['deviceTimezone'],
        'appIdentifier': value['appIdentifier'],
        'appPushToken': value['appPushToken'],
        'appPushBase64PublicKey': value['appPushBase64PublicKey'],
    };
}

