/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchResultType } from './SearchResultType';
import {
    SearchResultTypeFromJSON,
    SearchResultTypeFromJSONTyped,
    SearchResultTypeToJSON,
} from './SearchResultType';

/**
 * 
 * @export
 * @interface SearchResultDto
 */
export interface SearchResultDto {
    /**
     * 
     * @type {string}
     * @memberof SearchResultDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResultDto
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResultDto
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResultDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResultDto
     */
    teaser: string;
    /**
     * 
     * @type {SearchResultType}
     * @memberof SearchResultDto
     */
    type: SearchResultType;
}

/**
 * Check if a given object implements the SearchResultDto interface.
 */
export function instanceOfSearchResultDto(value: object): value is SearchResultDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('teaser' in value) || value['teaser'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function SearchResultDtoFromJSON(json: any): SearchResultDto {
    return SearchResultDtoFromJSONTyped(json, false);
}

export function SearchResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'projectId': json['projectId'],
        'title': json['title'] == null ? undefined : json['title'],
        'teaser': json['teaser'],
        'type': SearchResultTypeFromJSON(json['type']),
    };
}

export function SearchResultDtoToJSON(value?: SearchResultDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'projectId': value['projectId'],
        'title': value['title'],
        'teaser': value['teaser'],
        'type': SearchResultTypeToJSON(value['type']),
    };
}

