/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SharingState = {
    NotShared: 'notShared',
    SharedByMe: 'sharedByMe',
    SharedWithMe: 'sharedWithMe'
} as const;
export type SharingState = typeof SharingState[keyof typeof SharingState];


export function instanceOfSharingState(value: any): boolean {
    for (const key in SharingState) {
        if (Object.prototype.hasOwnProperty.call(SharingState, key)) {
            if (SharingState[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SharingStateFromJSON(json: any): SharingState {
    return SharingStateFromJSONTyped(json, false);
}

export function SharingStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharingState {
    return json as SharingState;
}

export function SharingStateToJSON(value?: SharingState | null): any {
    return value as any;
}

