/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionValidation } from './QuestionValidation';
import {
    QuestionValidationFromJSON,
    QuestionValidationFromJSONTyped,
    QuestionValidationToJSON,
} from './QuestionValidation';

/**
 * 
 * @export
 * @interface SliderQuestionValidation
 */
export interface SliderQuestionValidation extends QuestionValidation {
    /**
     * 
     * @type {number}
     * @memberof SliderQuestionValidation
     */
    min: number;
    /**
     * 
     * @type {number}
     * @memberof SliderQuestionValidation
     */
    max: number;
}

/**
 * Check if a given object implements the SliderQuestionValidation interface.
 */
export function instanceOfSliderQuestionValidation(value: object): value is SliderQuestionValidation {
    if (!('min' in value) || value['min'] === undefined) return false;
    if (!('max' in value) || value['max'] === undefined) return false;
    return true;
}

export function SliderQuestionValidationFromJSON(json: any): SliderQuestionValidation {
    return SliderQuestionValidationFromJSONTyped(json, false);
}

export function SliderQuestionValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SliderQuestionValidation {
    if (json == null) {
        return json;
    }
    return {
        ...QuestionValidationFromJSONTyped(json, ignoreDiscriminator),
        'min': json['min'],
        'max': json['max'],
    };
}

export function SliderQuestionValidationToJSON(value?: SliderQuestionValidation | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...QuestionValidationToJSON(value),
        'min': value['min'],
        'max': value['max'],
    };
}

