/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TenantParticipationState } from './TenantParticipationState';
import {
    instanceOfTenantParticipationState,
    TenantParticipationStateFromJSON,
    TenantParticipationStateFromJSONTyped,
    TenantParticipationStateToJSON,
} from './TenantParticipationState';

/**
 * @type TenantDtoParticipationState
 * 
 * @export
 */
export type TenantDtoParticipationState = TenantParticipationState;

export function TenantDtoParticipationStateFromJSON(json: any): TenantDtoParticipationState {
    return TenantDtoParticipationStateFromJSONTyped(json, false);
}

export function TenantDtoParticipationStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDtoParticipationState {
    if (json == null) {
        return json;
    }
    if (instanceOfTenantParticipationState(json)) {
        return TenantParticipationStateFromJSONTyped(json, true);
    }
}

export function TenantDtoParticipationStateToJSON(value?: TenantDtoParticipationState | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfTenantParticipationState(value)) {
        return TenantParticipationStateToJSON(value as TenantParticipationState);
    }

    return {};
}

