/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TextAnswerDto } from './TextAnswerDto';
import {
    instanceOfTextAnswerDto,
    TextAnswerDtoFromJSON,
    TextAnswerDtoFromJSONTyped,
    TextAnswerDtoToJSON,
} from './TextAnswerDto';

/**
 * @type TextQuestionDtoAllOfAnswer
 * 
 * @export
 */
export type TextQuestionDtoAllOfAnswer = TextAnswerDto;

export function TextQuestionDtoAllOfAnswerFromJSON(json: any): TextQuestionDtoAllOfAnswer {
    return TextQuestionDtoAllOfAnswerFromJSONTyped(json, false);
}

export function TextQuestionDtoAllOfAnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextQuestionDtoAllOfAnswer {
    if (json == null) {
        return json;
    }
    if (instanceOfTextAnswerDto(json)) {
        return TextAnswerDtoFromJSONTyped(json, true);
    }
}

export function TextQuestionDtoAllOfAnswerToJSON(value?: TextQuestionDtoAllOfAnswer | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfTextAnswerDto(value)) {
        return TextAnswerDtoToJSON(value as TextAnswerDto);
    }

    return {};
}

