/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionDtoAllOfHint } from './QuestionDtoAllOfHint';
import {
    QuestionDtoAllOfHintFromJSON,
    QuestionDtoAllOfHintFromJSONTyped,
    QuestionDtoAllOfHintToJSON,
} from './QuestionDtoAllOfHint';
import type { ElementType } from './ElementType';
import {
    ElementTypeFromJSON,
    ElementTypeFromJSONTyped,
    ElementTypeToJSON,
} from './ElementType';
import type { TimeQuestionValidation } from './TimeQuestionValidation';
import {
    TimeQuestionValidationFromJSON,
    TimeQuestionValidationFromJSONTyped,
    TimeQuestionValidationToJSON,
} from './TimeQuestionValidation';
import type { ContentDtoCondition } from './ContentDtoCondition';
import {
    ContentDtoConditionFromJSON,
    ContentDtoConditionFromJSONTyped,
    ContentDtoConditionToJSON,
} from './ContentDtoCondition';
import type { InternationalizedString } from './InternationalizedString';
import {
    InternationalizedStringFromJSON,
    InternationalizedStringFromJSONTyped,
    InternationalizedStringToJSON,
} from './InternationalizedString';
import type { QuestionDto } from './QuestionDto';
import {
    QuestionDtoFromJSON,
    QuestionDtoFromJSONTyped,
    QuestionDtoToJSON,
} from './QuestionDto';
import type { TimeQuestionDtoAllOfAnswer } from './TimeQuestionDtoAllOfAnswer';
import {
    TimeQuestionDtoAllOfAnswerFromJSON,
    TimeQuestionDtoAllOfAnswerFromJSONTyped,
    TimeQuestionDtoAllOfAnswerToJSON,
} from './TimeQuestionDtoAllOfAnswer';

/**
 * 
 * @export
 * @interface TimeQuestionDto
 */
export interface TimeQuestionDto extends QuestionDto {
    /**
     * 
     * @type {number}
     * @memberof TimeQuestionDto
     */
    minuteIncrements?: number;
    /**
     * 
     * @type {TimeQuestionValidation}
     * @memberof TimeQuestionDto
     */
    validation: TimeQuestionValidation;
    /**
     * 
     * @type {TimeQuestionDtoAllOfAnswer}
     * @memberof TimeQuestionDto
     */
    answer?: TimeQuestionDtoAllOfAnswer;
}

/**
 * Check if a given object implements the TimeQuestionDto interface.
 */
export function instanceOfTimeQuestionDto(value: object): value is TimeQuestionDto {
    if (!('validation' in value) || value['validation'] === undefined) return false;
    return true;
}

export function TimeQuestionDtoFromJSON(json: any): TimeQuestionDto {
    return TimeQuestionDtoFromJSONTyped(json, false);
}

export function TimeQuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeQuestionDto {
    if (json == null) {
        return json;
    }
    return {
        ...QuestionDtoFromJSONTyped(json, ignoreDiscriminator),
        'minuteIncrements': json['minuteIncrements'] == null ? undefined : json['minuteIncrements'],
        'validation': TimeQuestionValidationFromJSON(json['validation']),
        'answer': json['answer'] == null ? undefined : TimeQuestionDtoAllOfAnswerFromJSON(json['answer']),
    };
}

export function TimeQuestionDtoToJSON(value?: TimeQuestionDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...QuestionDtoToJSON(value),
        'minuteIncrements': value['minuteIncrements'],
        'validation': TimeQuestionValidationToJSON(value['validation']),
        'answer': TimeQuestionDtoAllOfAnswerToJSON(value['answer']),
    };
}

