/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnregisterAppInstallationCommand
 */
export interface UnregisterAppInstallationCommand {
    /**
     * 
     * @type {string}
     * @memberof UnregisterAppInstallationCommand
     */
    deviceIdentifier: string;
    /**
     * 
     * @type {string}
     * @memberof UnregisterAppInstallationCommand
     */
    appIdentifier: string;
}

/**
 * Check if a given object implements the UnregisterAppInstallationCommand interface.
 */
export function instanceOfUnregisterAppInstallationCommand(value: object): value is UnregisterAppInstallationCommand {
    if (!('deviceIdentifier' in value) || value['deviceIdentifier'] === undefined) return false;
    if (!('appIdentifier' in value) || value['appIdentifier'] === undefined) return false;
    return true;
}

export function UnregisterAppInstallationCommandFromJSON(json: any): UnregisterAppInstallationCommand {
    return UnregisterAppInstallationCommandFromJSONTyped(json, false);
}

export function UnregisterAppInstallationCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnregisterAppInstallationCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceIdentifier': json['deviceIdentifier'],
        'appIdentifier': json['appIdentifier'],
    };
}

export function UnregisterAppInstallationCommandToJSON(value?: UnregisterAppInstallationCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'deviceIdentifier': value['deviceIdentifier'],
        'appIdentifier': value['appIdentifier'],
    };
}

