/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionValidation } from './QuestionValidation';
import {
    QuestionValidationFromJSON,
    QuestionValidationFromJSONTyped,
    QuestionValidationToJSON,
} from './QuestionValidation';

/**
 * 
 * @export
 * @interface ChoiceQuestionValidation
 */
export interface ChoiceQuestionValidation extends QuestionValidation {
}

/**
 * Check if a given object implements the ChoiceQuestionValidation interface.
 */
export function instanceOfChoiceQuestionValidation(value: object): value is ChoiceQuestionValidation {
    return true;
}

export function ChoiceQuestionValidationFromJSON(json: any): ChoiceQuestionValidation {
    return ChoiceQuestionValidationFromJSONTyped(json, false);
}

export function ChoiceQuestionValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChoiceQuestionValidation {
    return json;
}

export function ChoiceQuestionValidationToJSON(value?: ChoiceQuestionValidation | null): any {
    return value;
}

