/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentDto } from './ContentDto';
import {
    ContentDtoFromJSON,
    ContentDtoFromJSONTyped,
    ContentDtoToJSON,
} from './ContentDto';
import type { AppPageDetailsDtoCondition } from './AppPageDetailsDtoCondition';
import {
    AppPageDetailsDtoConditionFromJSON,
    AppPageDetailsDtoConditionFromJSONTyped,
    AppPageDetailsDtoConditionToJSON,
} from './AppPageDetailsDtoCondition';
import type { LanguageDto } from './LanguageDto';
import {
    LanguageDtoFromJSON,
    LanguageDtoFromJSONTyped,
    LanguageDtoToJSON,
} from './LanguageDto';
import type { InternationalizedString } from './InternationalizedString';
import {
    InternationalizedStringFromJSON,
    InternationalizedStringFromJSONTyped,
    InternationalizedStringToJSON,
} from './InternationalizedString';
import type { InternationalizedDocument } from './InternationalizedDocument';
import {
    InternationalizedDocumentFromJSON,
    InternationalizedDocumentFromJSONTyped,
    InternationalizedDocumentToJSON,
} from './InternationalizedDocument';

/**
 * 
 * @export
 * @interface ContextObjectDetailsDto
 */
export interface ContextObjectDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof ContextObjectDetailsDto
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof ContextObjectDetailsDto
     */
    version: number;
    /**
     * 
     * @type {string}
     * @memberof ContextObjectDetailsDto
     */
    name: string;
    /**
     * 
     * @type {InternationalizedString}
     * @memberof ContextObjectDetailsDto
     */
    title: InternationalizedString;
    /**
     * 
     * @type {InternationalizedDocument}
     * @memberof ContextObjectDetailsDto
     */
    description: InternationalizedDocument;
    /**
     * 
     * @type {Date}
     * @memberof ContextObjectDetailsDto
     */
    lastModified: Date;
    /**
     * 
     * @type {Date}
     * @memberof ContextObjectDetailsDto
     */
    published?: Date;
    /**
     * 
     * @type {Array<ContentDto>}
     * @memberof ContextObjectDetailsDto
     */
    contents: Array<ContentDto>;
    /**
     * 
     * @type {LanguageDto}
     * @memberof ContextObjectDetailsDto
     */
    defaultLanguage: LanguageDto;
    /**
     * 
     * @type {Array<LanguageDto>}
     * @memberof ContextObjectDetailsDto
     */
    languages: Array<LanguageDto>;
    /**
     * 
     * @type {AppPageDetailsDtoCondition}
     * @memberof ContextObjectDetailsDto
     */
    condition?: AppPageDetailsDtoCondition;
}

/**
 * Check if a given object implements the ContextObjectDetailsDto interface.
 */
export function instanceOfContextObjectDetailsDto(value: object): value is ContextObjectDetailsDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('lastModified' in value) || value['lastModified'] === undefined) return false;
    if (!('contents' in value) || value['contents'] === undefined) return false;
    if (!('defaultLanguage' in value) || value['defaultLanguage'] === undefined) return false;
    if (!('languages' in value) || value['languages'] === undefined) return false;
    return true;
}

export function ContextObjectDetailsDtoFromJSON(json: any): ContextObjectDetailsDto {
    return ContextObjectDetailsDtoFromJSONTyped(json, false);
}

export function ContextObjectDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContextObjectDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'version': json['version'],
        'name': json['name'],
        'title': InternationalizedStringFromJSON(json['title']),
        'description': InternationalizedDocumentFromJSON(json['description']),
        'lastModified': (new Date(json['lastModified'])),
        'published': json['published'] == null ? undefined : (new Date(json['published'])),
        'contents': ((json['contents'] as Array<any>).map(ContentDtoFromJSON)),
        'defaultLanguage': LanguageDtoFromJSON(json['defaultLanguage']),
        'languages': ((json['languages'] as Array<any>).map(LanguageDtoFromJSON)),
        'condition': json['condition'] == null ? undefined : AppPageDetailsDtoConditionFromJSON(json['condition']),
    };
}

export function ContextObjectDetailsDtoToJSON(value?: ContextObjectDetailsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'version': value['version'],
        'name': value['name'],
        'title': InternationalizedStringToJSON(value['title']),
        'description': InternationalizedDocumentToJSON(value['description']),
        'lastModified': ((value['lastModified']).toISOString()),
        'published': value['published'] == null ? undefined : ((value['published'] as any).toISOString()),
        'contents': ((value['contents'] as Array<any>).map(ContentDtoToJSON)),
        'defaultLanguage': LanguageDtoToJSON(value['defaultLanguage']),
        'languages': ((value['languages'] as Array<any>).map(LanguageDtoToJSON)),
        'condition': AppPageDetailsDtoConditionToJSON(value['condition']),
    };
}

