/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAssetFolderCommand
 */
export interface CreateAssetFolderCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateAssetFolderCommand
     */
    parentId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAssetFolderCommand
     */
    name: string;
}

/**
 * Check if a given object implements the CreateAssetFolderCommand interface.
 */
export function instanceOfCreateAssetFolderCommand(value: object): value is CreateAssetFolderCommand {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateAssetFolderCommandFromJSON(json: any): CreateAssetFolderCommand {
    return CreateAssetFolderCommandFromJSONTyped(json, false);
}

export function CreateAssetFolderCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAssetFolderCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'name': json['name'],
    };
}

export function CreateAssetFolderCommandToJSON(value?: CreateAssetFolderCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'parentId': value['parentId'],
        'name': value['name'],
    };
}

