/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAppPageCommand
 */
export interface CreateAppPageCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateAppPageCommand
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAppPageCommand
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAppPageCommand
     */
    parentPageId?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateAppPageCommand
     */
    index: number;
}

/**
 * Check if a given object implements the CreateAppPageCommand interface.
 */
export function instanceOfCreateAppPageCommand(value: object): value is CreateAppPageCommand {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    return true;
}

export function CreateAppPageCommandFromJSON(json: any): CreateAppPageCommand {
    return CreateAppPageCommandFromJSONTyped(json, false);
}

export function CreateAppPageCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAppPageCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'projectId': json['projectId'],
        'parentPageId': json['parentPageId'] == null ? undefined : json['parentPageId'],
        'index': json['index'],
    };
}

export function CreateAppPageCommandToJSON(value?: CreateAppPageCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'projectId': value['projectId'],
        'parentPageId': value['parentPageId'],
        'index': value['index'],
    };
}

