/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceDetailsDto } from './DeviceDetailsDto';
import {
    DeviceDetailsDtoFromJSON,
    DeviceDetailsDtoFromJSONTyped,
    DeviceDetailsDtoToJSON,
} from './DeviceDetailsDto';

/**
 * 
 * @export
 * @interface MobilePhoneDetailsDto
 */
export interface MobilePhoneDetailsDto extends DeviceDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof MobilePhoneDetailsDto
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof MobilePhoneDetailsDto
     */
    osVersion: string;
    /**
     * 
     * @type {string}
     * @memberof MobilePhoneDetailsDto
     */
    language: string;
    /**
     * 
     * @type {string}
     * @memberof MobilePhoneDetailsDto
     */
    timezone: string;
}

/**
 * Check if a given object implements the MobilePhoneDetailsDto interface.
 */
export function instanceOfMobilePhoneDetailsDto(value: object): value is MobilePhoneDetailsDto {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('osVersion' in value) || value['osVersion'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    return true;
}

export function MobilePhoneDetailsDtoFromJSON(json: any): MobilePhoneDetailsDto {
    return MobilePhoneDetailsDtoFromJSONTyped(json, false);
}

export function MobilePhoneDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MobilePhoneDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        ...DeviceDetailsDtoFromJSONTyped(json, ignoreDiscriminator),
        'model': json['model'],
        'osVersion': json['osVersion'],
        'language': json['language'],
        'timezone': json['timezone'],
    };
}

export function MobilePhoneDetailsDtoToJSON(value?: MobilePhoneDetailsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...DeviceDetailsDtoToJSON(value),
        'model': value['model'],
        'osVersion': value['osVersion'],
        'language': value['language'],
        'timezone': value['timezone'],
    };
}

