/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoveAssetFolderCommand
 */
export interface MoveAssetFolderCommand {
    /**
     * 
     * @type {string}
     * @memberof MoveAssetFolderCommand
     */
    assetFolderId: string;
    /**
     * 
     * @type {string}
     * @memberof MoveAssetFolderCommand
     */
    parentId: string;
}

/**
 * Check if a given object implements the MoveAssetFolderCommand interface.
 */
export function instanceOfMoveAssetFolderCommand(value: object): value is MoveAssetFolderCommand {
    if (!('assetFolderId' in value) || value['assetFolderId'] === undefined) return false;
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    return true;
}

export function MoveAssetFolderCommandFromJSON(json: any): MoveAssetFolderCommand {
    return MoveAssetFolderCommandFromJSONTyped(json, false);
}

export function MoveAssetFolderCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoveAssetFolderCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'assetFolderId': json['assetFolderId'],
        'parentId': json['parentId'],
    };
}

export function MoveAssetFolderCommandToJSON(value?: MoveAssetFolderCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'assetFolderId': value['assetFolderId'],
        'parentId': value['parentId'],
    };
}

