/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoveAssetCommand
 */
export interface MoveAssetCommand {
    /**
     * 
     * @type {string}
     * @memberof MoveAssetCommand
     */
    assetId: string;
    /**
     * 
     * @type {string}
     * @memberof MoveAssetCommand
     */
    assetFolderId: string;
}

/**
 * Check if a given object implements the MoveAssetCommand interface.
 */
export function instanceOfMoveAssetCommand(value: object): value is MoveAssetCommand {
    if (!('assetId' in value) || value['assetId'] === undefined) return false;
    if (!('assetFolderId' in value) || value['assetFolderId'] === undefined) return false;
    return true;
}

export function MoveAssetCommandFromJSON(json: any): MoveAssetCommand {
    return MoveAssetCommandFromJSONTyped(json, false);
}

export function MoveAssetCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoveAssetCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'assetId': json['assetId'],
        'assetFolderId': json['assetFolderId'],
    };
}

export function MoveAssetCommandToJSON(value?: MoveAssetCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'assetId': value['assetId'],
        'assetFolderId': value['assetFolderId'],
    };
}

