/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NodeType = {
    Blockquote: 'blockquote',
    BulletList: 'bulletList',
    Doc: 'doc',
    HardBreak: 'hardBreak',
    Heading: 'heading',
    HorizontalRule: 'horizontalRule',
    ListItem: 'listItem',
    OrderedList: 'orderedList',
    Paragraph: 'paragraph',
    Table: 'table',
    TableRow: 'tableRow',
    TableHeader: 'tableHeader',
    TableCell: 'tableCell',
    Text: 'text',
    Video: 'video',
    Audio: 'audio',
    Image: 'image',
    Html: 'html'
} as const;
export type NodeType = typeof NodeType[keyof typeof NodeType];


export function instanceOfNodeType(value: any): boolean {
    for (const key in NodeType) {
        if (Object.prototype.hasOwnProperty.call(NodeType, key)) {
            if (NodeType[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NodeTypeFromJSON(json: any): NodeType {
    return NodeTypeFromJSONTyped(json, false);
}

export function NodeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeType {
    return json as NodeType;
}

export function NodeTypeToJSON(value?: NodeType | null): any {
    return value as any;
}

