/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectAdministratorDto } from './ProjectAdministratorDto';
import {
    ProjectAdministratorDtoFromJSON,
    ProjectAdministratorDtoFromJSONTyped,
    ProjectAdministratorDtoToJSON,
} from './ProjectAdministratorDto';

/**
 * 
 * @export
 * @interface PaginatedListOfProjectAdministratorDto
 */
export interface PaginatedListOfProjectAdministratorDto {
    /**
     * 
     * @type {Array<ProjectAdministratorDto>}
     * @memberof PaginatedListOfProjectAdministratorDto
     */
    items: Array<ProjectAdministratorDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfProjectAdministratorDto
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfProjectAdministratorDto
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfProjectAdministratorDto
     */
    totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfProjectAdministratorDto
     */
    hasPreviousPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfProjectAdministratorDto
     */
    hasNextPage: boolean;
}

/**
 * Check if a given object implements the PaginatedListOfProjectAdministratorDto interface.
 */
export function instanceOfPaginatedListOfProjectAdministratorDto(value: object): value is PaginatedListOfProjectAdministratorDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    return true;
}

export function PaginatedListOfProjectAdministratorDtoFromJSON(json: any): PaginatedListOfProjectAdministratorDto {
    return PaginatedListOfProjectAdministratorDtoFromJSONTyped(json, false);
}

export function PaginatedListOfProjectAdministratorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListOfProjectAdministratorDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ProjectAdministratorDtoFromJSON)),
        'pageNumber': json['pageNumber'],
        'totalPages': json['totalPages'],
        'totalCount': json['totalCount'],
        'hasPreviousPage': json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'],
    };
}

export function PaginatedListOfProjectAdministratorDtoToJSON(value?: PaginatedListOfProjectAdministratorDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(ProjectAdministratorDtoToJSON)),
        'pageNumber': value['pageNumber'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

