/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetDto } from './AssetDto';
import {
    AssetDtoFromJSON,
    AssetDtoFromJSONTyped,
    AssetDtoToJSON,
} from './AssetDto';

/**
 * 
 * @export
 * @interface PaginatedListOfAssetDto
 */
export interface PaginatedListOfAssetDto {
    /**
     * 
     * @type {Array<AssetDto>}
     * @memberof PaginatedListOfAssetDto
     */
    items: Array<AssetDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfAssetDto
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfAssetDto
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfAssetDto
     */
    totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfAssetDto
     */
    hasPreviousPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfAssetDto
     */
    hasNextPage: boolean;
}

/**
 * Check if a given object implements the PaginatedListOfAssetDto interface.
 */
export function instanceOfPaginatedListOfAssetDto(value: object): value is PaginatedListOfAssetDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    return true;
}

export function PaginatedListOfAssetDtoFromJSON(json: any): PaginatedListOfAssetDto {
    return PaginatedListOfAssetDtoFromJSONTyped(json, false);
}

export function PaginatedListOfAssetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListOfAssetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AssetDtoFromJSON)),
        'pageNumber': json['pageNumber'],
        'totalPages': json['totalPages'],
        'totalCount': json['totalCount'],
        'hasPreviousPage': json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'],
    };
}

export function PaginatedListOfAssetDtoToJSON(value?: PaginatedListOfAssetDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(AssetDtoToJSON)),
        'pageNumber': value['pageNumber'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

