/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScheduleDto } from './ScheduleDto';
import {
    ScheduleDtoFromJSON,
    ScheduleDtoFromJSONTyped,
    ScheduleDtoToJSON,
} from './ScheduleDto';

/**
 * 
 * @export
 * @interface PaginatedListOfScheduleDto
 */
export interface PaginatedListOfScheduleDto {
    /**
     * 
     * @type {Array<ScheduleDto>}
     * @memberof PaginatedListOfScheduleDto
     */
    items: Array<ScheduleDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfScheduleDto
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfScheduleDto
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfScheduleDto
     */
    totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfScheduleDto
     */
    hasPreviousPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfScheduleDto
     */
    hasNextPage: boolean;
}

/**
 * Check if a given object implements the PaginatedListOfScheduleDto interface.
 */
export function instanceOfPaginatedListOfScheduleDto(value: object): value is PaginatedListOfScheduleDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    return true;
}

export function PaginatedListOfScheduleDtoFromJSON(json: any): PaginatedListOfScheduleDto {
    return PaginatedListOfScheduleDtoFromJSONTyped(json, false);
}

export function PaginatedListOfScheduleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListOfScheduleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ScheduleDtoFromJSON)),
        'pageNumber': json['pageNumber'],
        'totalPages': json['totalPages'],
        'totalCount': json['totalCount'],
        'hasPreviousPage': json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'],
    };
}

export function PaginatedListOfScheduleDtoToJSON(value?: PaginatedListOfScheduleDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(ScheduleDtoToJSON)),
        'pageNumber': value['pageNumber'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

