/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionnaireInstancesPerDayDto } from './QuestionnaireInstancesPerDayDto';
import {
    QuestionnaireInstancesPerDayDtoFromJSON,
    QuestionnaireInstancesPerDayDtoFromJSONTyped,
    QuestionnaireInstancesPerDayDtoToJSON,
} from './QuestionnaireInstancesPerDayDto';

/**
 * 
 * @export
 * @interface QuestionnaireInstanceStatisticsDto
 */
export interface QuestionnaireInstanceStatisticsDto {
    /**
     * 
     * @type {number}
     * @memberof QuestionnaireInstanceStatisticsDto
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof QuestionnaireInstanceStatisticsDto
     */
    amountCompleted: number;
    /**
     * 
     * @type {number}
     * @memberof QuestionnaireInstanceStatisticsDto
     */
    averageAmountCompletedPerDay: number;
    /**
     * 
     * @type {Array<QuestionnaireInstancesPerDayDto>}
     * @memberof QuestionnaireInstanceStatisticsDto
     */
    questionnaireInstancesPerDay: Array<QuestionnaireInstancesPerDayDto>;
}

/**
 * Check if a given object implements the QuestionnaireInstanceStatisticsDto interface.
 */
export function instanceOfQuestionnaireInstanceStatisticsDto(value: object): value is QuestionnaireInstanceStatisticsDto {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('amountCompleted' in value) || value['amountCompleted'] === undefined) return false;
    if (!('averageAmountCompletedPerDay' in value) || value['averageAmountCompletedPerDay'] === undefined) return false;
    if (!('questionnaireInstancesPerDay' in value) || value['questionnaireInstancesPerDay'] === undefined) return false;
    return true;
}

export function QuestionnaireInstanceStatisticsDtoFromJSON(json: any): QuestionnaireInstanceStatisticsDto {
    return QuestionnaireInstanceStatisticsDtoFromJSONTyped(json, false);
}

export function QuestionnaireInstanceStatisticsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionnaireInstanceStatisticsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'amountCompleted': json['amountCompleted'],
        'averageAmountCompletedPerDay': json['averageAmountCompletedPerDay'],
        'questionnaireInstancesPerDay': ((json['questionnaireInstancesPerDay'] as Array<any>).map(QuestionnaireInstancesPerDayDtoFromJSON)),
    };
}

export function QuestionnaireInstanceStatisticsDtoToJSON(value?: QuestionnaireInstanceStatisticsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'amountCompleted': value['amountCompleted'],
        'averageAmountCompletedPerDay': value['averageAmountCompletedPerDay'],
        'questionnaireInstancesPerDay': ((value['questionnaireInstancesPerDay'] as Array<any>).map(QuestionnaireInstancesPerDayDtoToJSON)),
    };
}

