/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ProjectParticipantDto } from './ProjectParticipantDto';
import {
    instanceOfProjectParticipantDto,
    ProjectParticipantDtoFromJSON,
    ProjectParticipantDtoFromJSONTyped,
    ProjectParticipantDtoToJSON,
} from './ProjectParticipantDto';

/**
 * @type QuestionnaireInstanceDetailsDtoAllOfOwner
 * 
 * @export
 */
export type QuestionnaireInstanceDetailsDtoAllOfOwner = ProjectParticipantDto;

export function QuestionnaireInstanceDetailsDtoAllOfOwnerFromJSON(json: any): QuestionnaireInstanceDetailsDtoAllOfOwner {
    return QuestionnaireInstanceDetailsDtoAllOfOwnerFromJSONTyped(json, false);
}

export function QuestionnaireInstanceDetailsDtoAllOfOwnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionnaireInstanceDetailsDtoAllOfOwner {
    if (json == null) {
        return json;
    }
    if (instanceOfProjectParticipantDto(json)) {
        return ProjectParticipantDtoFromJSONTyped(json, true);
    }
}

export function QuestionnaireInstanceDetailsDtoAllOfOwnerToJSON(value?: QuestionnaireInstanceDetailsDtoAllOfOwner | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfProjectParticipantDto(value)) {
        return ProjectParticipantDtoToJSON(value as ProjectParticipantDto);
    }

    return {};
}

