/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionStatisticsDto
 */
export interface QuestionStatisticsDto {
    /**
     * 
     * @type {number}
     * @memberof QuestionStatisticsDto
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof QuestionStatisticsDto
     */
    averageAmountAnswers: number;
    /**
     * 
     * @type {number}
     * @memberof QuestionStatisticsDto
     */
    averageAmountAnsweredAnswers: number;
}

/**
 * Check if a given object implements the QuestionStatisticsDto interface.
 */
export function instanceOfQuestionStatisticsDto(value: object): value is QuestionStatisticsDto {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('averageAmountAnswers' in value) || value['averageAmountAnswers'] === undefined) return false;
    if (!('averageAmountAnsweredAnswers' in value) || value['averageAmountAnsweredAnswers'] === undefined) return false;
    return true;
}

export function QuestionStatisticsDtoFromJSON(json: any): QuestionStatisticsDto {
    return QuestionStatisticsDtoFromJSONTyped(json, false);
}

export function QuestionStatisticsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionStatisticsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'averageAmountAnswers': json['averageAmountAnswers'],
        'averageAmountAnsweredAnswers': json['averageAmountAnsweredAnswers'],
    };
}

export function QuestionStatisticsDtoToJSON(value?: QuestionStatisticsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'averageAmountAnswers': value['averageAmountAnswers'],
        'averageAmountAnsweredAnswers': value['averageAmountAnsweredAnswers'],
    };
}

