/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { LanguageDto } from './LanguageDto';
import {
    instanceOfLanguageDto,
    LanguageDtoFromJSON,
    LanguageDtoFromJSONTyped,
    LanguageDtoToJSON,
} from './LanguageDto';

/**
 * @type QuestionnaireInstanceDetailsDtoAllOfExecutionLanguage
 * 
 * @export
 */
export type QuestionnaireInstanceDetailsDtoAllOfExecutionLanguage = LanguageDto;

export function QuestionnaireInstanceDetailsDtoAllOfExecutionLanguageFromJSON(json: any): QuestionnaireInstanceDetailsDtoAllOfExecutionLanguage {
    return QuestionnaireInstanceDetailsDtoAllOfExecutionLanguageFromJSONTyped(json, false);
}

export function QuestionnaireInstanceDetailsDtoAllOfExecutionLanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionnaireInstanceDetailsDtoAllOfExecutionLanguage {
    if (json == null) {
        return json;
    }
    if (instanceOfLanguageDto(json)) {
        return LanguageDtoFromJSONTyped(json, true);
    }
}

export function QuestionnaireInstanceDetailsDtoAllOfExecutionLanguageToJSON(value?: QuestionnaireInstanceDetailsDtoAllOfExecutionLanguage | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfLanguageDto(value)) {
        return LanguageDtoToJSON(value as LanguageDto);
    }

    return {};
}

