/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const QuestionnaireInstantiationMode = {
    None: 'none',
    Manual: 'manual',
    Auto: 'auto',
    Both: 'both'
} as const;
export type QuestionnaireInstantiationMode = typeof QuestionnaireInstantiationMode[keyof typeof QuestionnaireInstantiationMode];


export function instanceOfQuestionnaireInstantiationMode(value: any): boolean {
    for (const key in QuestionnaireInstantiationMode) {
        if (Object.prototype.hasOwnProperty.call(QuestionnaireInstantiationMode, key)) {
            if (QuestionnaireInstantiationMode[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function QuestionnaireInstantiationModeFromJSON(json: any): QuestionnaireInstantiationMode {
    return QuestionnaireInstantiationModeFromJSONTyped(json, false);
}

export function QuestionnaireInstantiationModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionnaireInstantiationMode {
    return json as QuestionnaireInstantiationMode;
}

export function QuestionnaireInstantiationModeToJSON(value?: QuestionnaireInstantiationMode | null): any {
    return value as any;
}

