/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DisplayDto } from './DisplayDto';
import {
    DisplayDtoFromJSON,
    DisplayDtoFromJSONTyped,
    DisplayDtoToJSON,
} from './DisplayDto';
import type { ElementType } from './ElementType';
import {
    ElementTypeFromJSON,
    ElementTypeFromJSONTyped,
    ElementTypeToJSON,
} from './ElementType';
import type { ContentDtoCondition } from './ContentDtoCondition';
import {
    ContentDtoConditionFromJSON,
    ContentDtoConditionFromJSONTyped,
    ContentDtoConditionToJSON,
} from './ContentDtoCondition';
import type { InternationalizedDocument } from './InternationalizedDocument';
import {
    InternationalizedDocumentFromJSON,
    InternationalizedDocumentFromJSONTyped,
    InternationalizedDocumentToJSON,
} from './InternationalizedDocument';

/**
 * 
 * @export
 * @interface RichTextDisplayDto
 */
export interface RichTextDisplayDto extends DisplayDto {
    /**
     * 
     * @type {InternationalizedDocument}
     * @memberof RichTextDisplayDto
     */
    value: InternationalizedDocument;
}

/**
 * Check if a given object implements the RichTextDisplayDto interface.
 */
export function instanceOfRichTextDisplayDto(value: object): value is RichTextDisplayDto {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function RichTextDisplayDtoFromJSON(json: any): RichTextDisplayDto {
    return RichTextDisplayDtoFromJSONTyped(json, false);
}

export function RichTextDisplayDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RichTextDisplayDto {
    if (json == null) {
        return json;
    }
    return {
        ...DisplayDtoFromJSONTyped(json, ignoreDiscriminator),
        'value': InternationalizedDocumentFromJSON(json['value']),
    };
}

export function RichTextDisplayDtoToJSON(value?: RichTextDisplayDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...DisplayDtoToJSON(value),
        'value': InternationalizedDocumentToJSON(value['value']),
    };
}

