/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetDefaultLanguageCommand
 */
export interface SetDefaultLanguageCommand {
    /**
     * 
     * @type {string}
     * @memberof SetDefaultLanguageCommand
     */
    languageId: string;
}

/**
 * Check if a given object implements the SetDefaultLanguageCommand interface.
 */
export function instanceOfSetDefaultLanguageCommand(value: object): value is SetDefaultLanguageCommand {
    if (!('languageId' in value) || value['languageId'] === undefined) return false;
    return true;
}

export function SetDefaultLanguageCommandFromJSON(json: any): SetDefaultLanguageCommand {
    return SetDefaultLanguageCommandFromJSONTyped(json, false);
}

export function SetDefaultLanguageCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetDefaultLanguageCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'languageId': json['languageId'],
    };
}

export function SetDefaultLanguageCommandToJSON(value?: SetDefaultLanguageCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'languageId': value['languageId'],
    };
}

