/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SliderAnswerDto } from './SliderAnswerDto';
import {
    instanceOfSliderAnswerDto,
    SliderAnswerDtoFromJSON,
    SliderAnswerDtoFromJSONTyped,
    SliderAnswerDtoToJSON,
} from './SliderAnswerDto';

/**
 * @type SliderQuestionDtoAllOfAnswer
 * 
 * @export
 */
export type SliderQuestionDtoAllOfAnswer = SliderAnswerDto;

export function SliderQuestionDtoAllOfAnswerFromJSON(json: any): SliderQuestionDtoAllOfAnswer {
    return SliderQuestionDtoAllOfAnswerFromJSONTyped(json, false);
}

export function SliderQuestionDtoAllOfAnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SliderQuestionDtoAllOfAnswer {
    if (json == null) {
        return json;
    }
    if (instanceOfSliderAnswerDto(json)) {
        return SliderAnswerDtoFromJSONTyped(json, true);
    }
}

export function SliderQuestionDtoAllOfAnswerToJSON(value?: SliderQuestionDtoAllOfAnswer | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfSliderAnswerDto(value)) {
        return SliderAnswerDtoToJSON(value as SliderAnswerDto);
    }

    return {};
}

