/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantEntityDto
 */
export interface TenantEntityDto {
    /**
     * 
     * @type {string}
     * @memberof TenantEntityDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TenantEntityDto
     */
    tenantId: string;
}

/**
 * Check if a given object implements the TenantEntityDto interface.
 */
export function instanceOfTenantEntityDto(value: object): value is TenantEntityDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function TenantEntityDtoFromJSON(json: any): TenantEntityDto {
    return TenantEntityDtoFromJSONTyped(json, false);
}

export function TenantEntityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantEntityDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
    };
}

export function TenantEntityDtoToJSON(value?: TenantEntityDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
    };
}

