/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantParticipantStatus } from './TenantParticipantStatus';
import {
    TenantParticipantStatusFromJSON,
    TenantParticipantStatusFromJSONTyped,
    TenantParticipantStatusToJSON,
} from './TenantParticipantStatus';
import type { UserDto } from './UserDto';
import {
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
} from './UserDto';

/**
 * 
 * @export
 * @interface TenantParticipantDto
 */
export interface TenantParticipantDto {
    /**
     * 
     * @type {UserDto}
     * @memberof TenantParticipantDto
     */
    user: UserDto;
    /**
     * 
     * @type {string}
     * @memberof TenantParticipantDto
     */
    tenantId: string;
    /**
     * 
     * @type {Date}
     * @memberof TenantParticipantDto
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TenantParticipantDto
     */
    invited?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TenantParticipantDto
     */
    enrolled?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TenantParticipantDto
     */
    withdrawn?: Date;
    /**
     * 
     * @type {TenantParticipantStatus}
     * @memberof TenantParticipantDto
     */
    status: TenantParticipantStatus;
}

/**
 * Check if a given object implements the TenantParticipantDto interface.
 */
export function instanceOfTenantParticipantDto(value: object): value is TenantParticipantDto {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TenantParticipantDtoFromJSON(json: any): TenantParticipantDto {
    return TenantParticipantDtoFromJSONTyped(json, false);
}

export function TenantParticipantDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantParticipantDto {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserDtoFromJSON(json['user']),
        'tenantId': json['tenantId'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'invited': json['invited'] == null ? undefined : (new Date(json['invited'])),
        'enrolled': json['enrolled'] == null ? undefined : (new Date(json['enrolled'])),
        'withdrawn': json['withdrawn'] == null ? undefined : (new Date(json['withdrawn'])),
        'status': TenantParticipantStatusFromJSON(json['status']),
    };
}

export function TenantParticipantDtoToJSON(value?: TenantParticipantDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': UserDtoToJSON(value['user']),
        'tenantId': value['tenantId'],
        'created': value['created'] == null ? undefined : ((value['created'] as any).toISOString()),
        'invited': value['invited'] == null ? undefined : ((value['invited'] as any).toISOString()),
        'enrolled': value['enrolled'] == null ? undefined : ((value['enrolled'] as any).toISOString()),
        'withdrawn': value['withdrawn'] == null ? undefined : ((value['withdrawn'] as any).toISOString()),
        'status': TenantParticipantStatusToJSON(value['status']),
    };
}

