/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDto } from './UserDto';
import {
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
} from './UserDto';
import type { Permission } from './Permission';
import {
    PermissionFromJSON,
    PermissionFromJSONTyped,
    PermissionToJSON,
} from './Permission';

/**
 * 
 * @export
 * @interface TenantAdministratorDto
 */
export interface TenantAdministratorDto {
    /**
     * 
     * @type {UserDto}
     * @memberof TenantAdministratorDto
     */
    user: UserDto;
    /**
     * 
     * @type {string}
     * @memberof TenantAdministratorDto
     */
    tenantId: string;
    /**
     * 
     * @type {Array<Permission>}
     * @memberof TenantAdministratorDto
     */
    permissions: Array<Permission>;
}

/**
 * Check if a given object implements the TenantAdministratorDto interface.
 */
export function instanceOfTenantAdministratorDto(value: object): value is TenantAdministratorDto {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function TenantAdministratorDtoFromJSON(json: any): TenantAdministratorDto {
    return TenantAdministratorDtoFromJSONTyped(json, false);
}

export function TenantAdministratorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantAdministratorDto {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserDtoFromJSON(json['user']),
        'tenantId': json['tenantId'],
        'permissions': ((json['permissions'] as Array<any>).map(PermissionFromJSON)),
    };
}

export function TenantAdministratorDtoToJSON(value?: TenantAdministratorDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': UserDtoToJSON(value['user']),
        'tenantId': value['tenantId'],
        'permissions': ((value['permissions'] as Array<any>).map(PermissionToJSON)),
    };
}

