/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionValidation } from './QuestionValidation';
import {
    QuestionValidationFromJSON,
    QuestionValidationFromJSONTyped,
    QuestionValidationToJSON,
} from './QuestionValidation';

/**
 * 
 * @export
 * @interface TextQuestionValidation
 */
export interface TextQuestionValidation extends QuestionValidation {
    /**
     * 
     * @type {number}
     * @memberof TextQuestionValidation
     */
    minLength?: number;
    /**
     * 
     * @type {number}
     * @memberof TextQuestionValidation
     */
    maxLength?: number;
}

/**
 * Check if a given object implements the TextQuestionValidation interface.
 */
export function instanceOfTextQuestionValidation(value: object): value is TextQuestionValidation {
    return true;
}

export function TextQuestionValidationFromJSON(json: any): TextQuestionValidation {
    return TextQuestionValidationFromJSONTyped(json, false);
}

export function TextQuestionValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextQuestionValidation {
    if (json == null) {
        return json;
    }
    return {
        ...QuestionValidationFromJSONTyped(json, ignoreDiscriminator),
        'minLength': json['minLength'] == null ? undefined : json['minLength'],
        'maxLength': json['maxLength'] == null ? undefined : json['maxLength'],
    };
}

export function TextQuestionValidationToJSON(value?: TextQuestionValidation | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...QuestionValidationToJSON(value),
        'minLength': value['minLength'],
        'maxLength': value['maxLength'],
    };
}

