/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TranslateQuestionnaireCommand
 */
export interface TranslateQuestionnaireCommand {
    /**
     * 
     * @type {string}
     * @memberof TranslateQuestionnaireCommand
     */
    containerId: string;
    /**
     * 
     * @type {string}
     * @memberof TranslateQuestionnaireCommand
     */
    fromLanguageId?: string;
    /**
     * 
     * @type {string}
     * @memberof TranslateQuestionnaireCommand
     */
    toLanguageId?: string;
}

/**
 * Check if a given object implements the TranslateQuestionnaireCommand interface.
 */
export function instanceOfTranslateQuestionnaireCommand(value: object): value is TranslateQuestionnaireCommand {
    if (!('containerId' in value) || value['containerId'] === undefined) return false;
    return true;
}

export function TranslateQuestionnaireCommandFromJSON(json: any): TranslateQuestionnaireCommand {
    return TranslateQuestionnaireCommandFromJSONTyped(json, false);
}

export function TranslateQuestionnaireCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranslateQuestionnaireCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'containerId': json['containerId'],
        'fromLanguageId': json['fromLanguageId'] == null ? undefined : json['fromLanguageId'],
        'toLanguageId': json['toLanguageId'] == null ? undefined : json['toLanguageId'],
    };
}

export function TranslateQuestionnaireCommandToJSON(value?: TranslateQuestionnaireCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'containerId': value['containerId'],
        'fromLanguageId': value['fromLanguageId'],
        'toLanguageId': value['toLanguageId'],
    };
}

