/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAssetFolderCommand
 */
export interface UpdateAssetFolderCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateAssetFolderCommand
     */
    assetFolderId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAssetFolderCommand
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAssetFolderCommand
     */
    description?: string;
}

/**
 * Check if a given object implements the UpdateAssetFolderCommand interface.
 */
export function instanceOfUpdateAssetFolderCommand(value: object): value is UpdateAssetFolderCommand {
    if (!('assetFolderId' in value) || value['assetFolderId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateAssetFolderCommandFromJSON(json: any): UpdateAssetFolderCommand {
    return UpdateAssetFolderCommandFromJSONTyped(json, false);
}

export function UpdateAssetFolderCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAssetFolderCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'assetFolderId': json['assetFolderId'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateAssetFolderCommandToJSON(value?: UpdateAssetFolderCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'assetFolderId': value['assetFolderId'],
        'name': value['name'],
        'description': value['description'],
    };
}

