/* tslint:disable */
/* eslint-disable */
/**
 * HSP Frontend Tenant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedListOfLanguageDto,
} from '../models/index';
import {
    PaginatedListOfLanguageDtoFromJSON,
    PaginatedListOfLanguageDtoToJSON,
} from '../models/index';

export interface LanguagesGetLanguagesRequest {
    pageNumber?: number;
    pageSize?: number;
    search?: string;
}

/**
 * 
 */
export class LanguagesApi extends runtime.BaseAPI {

    /**
     */
    async languagesGetLanguagesRaw(requestParameters: LanguagesGetLanguagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedListOfLanguageDto>> {
        const queryParameters: any = {};

        if (requestParameters['pageNumber'] != null) {
            queryParameters['pageNumber'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/public/languages`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedListOfLanguageDtoFromJSON(jsonValue));
    }

    /**
     */
    async languagesGetLanguages(requestParameters: LanguagesGetLanguagesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedListOfLanguageDto> {
        const response = await this.languagesGetLanguagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
