/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantDto } from './TenantDto';
import {
    TenantDtoFromJSON,
    TenantDtoFromJSONTyped,
    TenantDtoToJSON,
} from './TenantDto';

/**
 * 
 * @export
 * @interface PaginatedListOfTenantDto
 */
export interface PaginatedListOfTenantDto {
    /**
     * 
     * @type {Array<TenantDto>}
     * @memberof PaginatedListOfTenantDto
     */
    items: Array<TenantDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfTenantDto
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfTenantDto
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedListOfTenantDto
     */
    totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfTenantDto
     */
    hasPreviousPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedListOfTenantDto
     */
    hasNextPage: boolean;
}

/**
 * Check if a given object implements the PaginatedListOfTenantDto interface.
 */
export function instanceOfPaginatedListOfTenantDto(value: object): value is PaginatedListOfTenantDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    return true;
}

export function PaginatedListOfTenantDtoFromJSON(json: any): PaginatedListOfTenantDto {
    return PaginatedListOfTenantDtoFromJSONTyped(json, false);
}

export function PaginatedListOfTenantDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListOfTenantDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TenantDtoFromJSON)),
        'pageNumber': json['pageNumber'],
        'totalPages': json['totalPages'],
        'totalCount': json['totalCount'],
        'hasPreviousPage': json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'],
    };
}

export function PaginatedListOfTenantDtoToJSON(value?: PaginatedListOfTenantDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(TenantDtoToJSON)),
        'pageNumber': value['pageNumber'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

