/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudyDto } from './StudyDto';
import {
    StudyDtoFromJSON,
    StudyDtoFromJSONTyped,
    StudyDtoToJSON,
} from './StudyDto';
import type { TenantDto } from './TenantDto';
import {
    TenantDtoFromJSON,
    TenantDtoFromJSONTyped,
    TenantDtoToJSON,
} from './TenantDto';

/**
 * 
 * @export
 * @interface TenantStudyDto
 */
export interface TenantStudyDto {
    /**
     * 
     * @type {TenantDto}
     * @memberof TenantStudyDto
     */
    tenant: TenantDto;
    /**
     * 
     * @type {StudyDto}
     * @memberof TenantStudyDto
     */
    study: StudyDto;
}

/**
 * Check if a given object implements the TenantStudyDto interface.
 */
export function instanceOfTenantStudyDto(value: object): value is TenantStudyDto {
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    if (!('study' in value) || value['study'] === undefined) return false;
    return true;
}

export function TenantStudyDtoFromJSON(json: any): TenantStudyDto {
    return TenantStudyDtoFromJSONTyped(json, false);
}

export function TenantStudyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantStudyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tenant': TenantDtoFromJSON(json['tenant']),
        'study': StudyDtoFromJSON(json['study']),
    };
}

export function TenantStudyDtoToJSON(value?: TenantStudyDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tenant': TenantDtoToJSON(value['tenant']),
        'study': StudyDtoToJSON(value['study']),
    };
}

