/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantDto } from './TenantDto';
import {
    TenantDtoFromJSON,
    TenantDtoFromJSONTyped,
    TenantDtoToJSON,
} from './TenantDto';
import type { QuestionnaireDto } from './QuestionnaireDto';
import {
    QuestionnaireDtoFromJSON,
    QuestionnaireDtoFromJSONTyped,
    QuestionnaireDtoToJSON,
} from './QuestionnaireDto';

/**
 * 
 * @export
 * @interface TenantQuestionnaireDto
 */
export interface TenantQuestionnaireDto {
    /**
     * 
     * @type {TenantDto}
     * @memberof TenantQuestionnaireDto
     */
    tenant: TenantDto;
    /**
     * 
     * @type {QuestionnaireDto}
     * @memberof TenantQuestionnaireDto
     */
    questionnaire: QuestionnaireDto;
}

/**
 * Check if a given object implements the TenantQuestionnaireDto interface.
 */
export function instanceOfTenantQuestionnaireDto(value: object): value is TenantQuestionnaireDto {
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    if (!('questionnaire' in value) || value['questionnaire'] === undefined) return false;
    return true;
}

export function TenantQuestionnaireDtoFromJSON(json: any): TenantQuestionnaireDto {
    return TenantQuestionnaireDtoFromJSONTyped(json, false);
}

export function TenantQuestionnaireDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantQuestionnaireDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tenant': TenantDtoFromJSON(json['tenant']),
        'questionnaire': QuestionnaireDtoFromJSON(json['questionnaire']),
    };
}

export function TenantQuestionnaireDtoToJSON(value?: TenantQuestionnaireDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tenant': TenantDtoToJSON(value['tenant']),
        'questionnaire': QuestionnaireDtoToJSON(value['questionnaire']),
    };
}

