/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCurrentUserCommand
 */
export interface UpdateCurrentUserCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    honorificPrefix?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    givenName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    additionalName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    familyName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    honorificSuffix?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    streetAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    addressLevel1?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    addressLevel2?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    addressLevel3?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    addressLevel4?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    language?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateCurrentUserCommand
     */
    birthDay: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentUserCommand
     */
    sex?: string;
}

/**
 * Check if a given object implements the UpdateCurrentUserCommand interface.
 */
export function instanceOfUpdateCurrentUserCommand(value: object): value is UpdateCurrentUserCommand {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('birthDay' in value) || value['birthDay'] === undefined) return false;
    return true;
}

export function UpdateCurrentUserCommandFromJSON(json: any): UpdateCurrentUserCommand {
    return UpdateCurrentUserCommandFromJSONTyped(json, false);
}

export function UpdateCurrentUserCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCurrentUserCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'phoneNumber': json['phoneNumber'],
        'honorificPrefix': json['honorificPrefix'] == null ? undefined : json['honorificPrefix'],
        'givenName': json['givenName'] == null ? undefined : json['givenName'],
        'additionalName': json['additionalName'] == null ? undefined : json['additionalName'],
        'familyName': json['familyName'] == null ? undefined : json['familyName'],
        'honorificSuffix': json['honorificSuffix'] == null ? undefined : json['honorificSuffix'],
        'streetAddress': json['streetAddress'] == null ? undefined : json['streetAddress'],
        'addressLevel1': json['addressLevel1'] == null ? undefined : json['addressLevel1'],
        'addressLevel2': json['addressLevel2'] == null ? undefined : json['addressLevel2'],
        'addressLevel3': json['addressLevel3'] == null ? undefined : json['addressLevel3'],
        'addressLevel4': json['addressLevel4'] == null ? undefined : json['addressLevel4'],
        'country': json['country'] == null ? undefined : json['country'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'language': json['language'] == null ? undefined : json['language'],
        'birthDay': (new Date(json['birthDay'])),
        'sex': json['sex'] == null ? undefined : json['sex'],
    };
}

export function UpdateCurrentUserCommandToJSON(value?: UpdateCurrentUserCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'honorificPrefix': value['honorificPrefix'],
        'givenName': value['givenName'],
        'additionalName': value['additionalName'],
        'familyName': value['familyName'],
        'honorificSuffix': value['honorificSuffix'],
        'streetAddress': value['streetAddress'],
        'addressLevel1': value['addressLevel1'],
        'addressLevel2': value['addressLevel2'],
        'addressLevel3': value['addressLevel3'],
        'addressLevel4': value['addressLevel4'],
        'country': value['country'],
        'postalCode': value['postalCode'],
        'language': value['language'],
        'birthDay': ((value['birthDay']).toISOString().substring(0,10)),
        'sex': value['sex'],
    };
}

