/* tslint:disable */
/* eslint-disable */
/**
 * HSP Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTenantVersionsCommand
 */
export interface UpdateTenantVersionsCommand {
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateTenantVersionsCommand
     */
    tenantIds: Array<string>;
}

/**
 * Check if a given object implements the UpdateTenantVersionsCommand interface.
 */
export function instanceOfUpdateTenantVersionsCommand(value: object): value is UpdateTenantVersionsCommand {
    if (!('tenantIds' in value) || value['tenantIds'] === undefined) return false;
    return true;
}

export function UpdateTenantVersionsCommandFromJSON(json: any): UpdateTenantVersionsCommand {
    return UpdateTenantVersionsCommandFromJSONTyped(json, false);
}

export function UpdateTenantVersionsCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTenantVersionsCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'tenantIds': json['tenantIds'],
    };
}

export function UpdateTenantVersionsCommandToJSON(value?: UpdateTenantVersionsCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tenantIds': value['tenantIds'],
    };
}

